name: CI Build → Scan → Push → Deploy
on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Build & push service-a
      run: |
        docker build -t $DOCKERHUB_USERNAME/service-a:latest -f apps/service-a/Dockerfile apps/service-a
        docker push $DOCKERHUB_USERNAME/service-a:latest

    - name: Scan service-a with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKERHUB_USERNAME }}/service-a:latest
        severity: CRITICAL

    - name: Build & push service-b
      run: |
        docker build -t $DOCKERHUB_USERNAME/service-b:latest -f apps/service-b/Dockerfile apps/service-b
        docker push $DOCKERHUB_USERNAME/service-b:latest

    - name: Scan service-b with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKERHUB_USERNAME }}/service-b:latest
        severity: CRITICAL

    - name: Build & push frontend
      run: |
        docker build -t $DOCKERHUB_USERNAME/frontend:latest -f apps/frontend/Dockerfile apps/frontend
        docker push $DOCKERHUB_USERNAME/frontend:latest

    - name: Scan frontend with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKERHUB_USERNAME }}/frontend:latest
        severity: CRITICAL

    - name: Prepare kubeconfig (robust for runners)
      if: env.KUBECONFIG_DATA != ''
      run: |
        mkdir -p $RUNNER_TEMP/.kube
        echo "$KUBECONFIG_DATA" | base64 -d > $RUNNER_TEMP/.kube/config
        export KUBECONFIG=$RUNNER_TEMP/.kube/config
        kubectl config current-context || true



    - name: Deploy to OpenShift (if KUBECONFIG_DATA present)
      if: env.KUBECONFIG_DATA != ''
      run: |
        oc project abdulrafey5-dev
        oc apply -f infra/openshift/mariadb.yaml
        oc apply -f infra/openshift/service-a-deploy.yaml
        oc apply -f infra/openshift/service-b-deploy.yaml
        oc apply -f infra/openshift/frontend-deploy.yaml
